/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'surface': '#131313',
        'surface-dim': '#131313',
        'surface-bright': '#393939',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1b1b1b',
        'surface-container': '#1f1f1f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353535',
        'on-surface': '#e2e2e2',
        'on-surface-variant': '#b9ccb2',
        'inverse-surface': '#e2e2e2',
        'inverse-on-surface': '#303030',
        'outline': '#84967e',
        'outline-variant': '#3b4b37',
        'surface-tint': '#00e639',
        'primary': '#ebffe2',
        'on-primary': '#003907',
        'primary-container': '#00ff41',
        'on-primary-container': '#007117',
        'inverse-primary': '#006e16',
        'secondary': '#ffffff',
        'on-secondary': '#003737',
        'secondary-container': '#00fbfb',
        'on-secondary-container': '#007070',
        'tertiary': '#f9f9f8',
        'on-tertiary': '#2f3131',
        'tertiary-container': '#dcdcdc',
        'on-tertiary-container': '#606161',
        'error': '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#72ff70',
        'primary-fixed-dim': '#00e639',
        'on-primary-fixed': '#002203',
        'on-primary-fixed-variant': '#00530e',
        'secondary-fixed': '#00fbfb',
        'secondary-fixed-dim': '#00dddd',
        'on-secondary-fixed': '#002020',
        'on-secondary-fixed-variant': '#004f4f',
        'tertiary-fixed': '#e3e2e2',
        'tertiary-fixed-dim': '#c6c6c6',
        'on-tertiary-fixed': '#1a1c1c',
        'on-tertiary-fixed-variant': '#464747',
        'background': '#131313',
        'on-background': '#e2e2e2',
      },
      fontFamily: {
        'headline': ['"Space Grotesk"', 'sans-serif'],
        'body': ['"Work Sans"', 'sans-serif'],
        'mono': ['"Courier New"', 'monospace'],
      }
    },
  },
  plugins: [],
}
